### ISSUE TITLE
Wrong number parsing on systems in comma decimal separator

### ISSUE THREAD

**Issue by lennartb-** [mikekov/PngToCursor#1]
Hi,
in Program.cs:29 you split the list of hot sports by commas, which breaks the conversion process on systems where commas are used as decimal separators (e.g. german) and produces some funky looking cursors. This can easily be fixed by passing NumberFormatInfo.InvariantInfo to the `double.Parse()` method:

`var xys = hot_spots.Split(',').Select(s => double.Parse(s, NumberFormatInfo.InvariantInfo)); `

**Comment by mikekov** [comment]
Thank you, pushed out a fix.
